### ISSUE TITLE
Films not playable for me

### ISSUE THREAD

**Issue by mn113** [jamieu/plugin.video.mubi#16]
I have Kodi 17.1 on OpenElec 8. After authenticating, the plugin gets to the index page, but the films can't be played.

I logged these errors for a single play attempt:
```
19:18:53.272 T:1369432992 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
19:18:55.832 T:1369432992   ERROR: No handlers could be found for logger "mubi.Mubi"
19:18:55.841 T:1369432992  NOTICE: [xbmcswift2] Request for "/play/293" matches rule for function "play_film"
19:18:56.334 T:1369432992   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mubi/addon.py", line 35, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/storage/.kodi/addons/plugin.video.mubi/addon.py", line 30, in play_film
                                                mubi_url = mubi.get_play_url(identifier)
                                              File "/storage/.kodi/addons/plugin.video.mubi/resources/lib/mubi.py", line 138, in get_play_url
                                                video_data_url = video_data_elem.get("data-secure-url")
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--
19:18:56.845 T:1947435024   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.mubi/play/293]
 ```

Any ideas?

**Comment by alexjbush** [comment]
See [https://github.com/jamieu/plugin.video.mubi/pull/18](https://github.com/jamieu/plugin.video.mubi/pull/18), it's working for me now
